### ISSUE TITLE
Support setting the cookie's domain

### ISSUE THREAD

**Issue by nullfact0r** [jcs224/oak_sessions#11]
Hi,
as it seems, it's not possible to set the domain for the session cookie, only the value. This means that both the frontend and backend will need to run on the same domain, without subdomain or else the browser won't set the cookie.

Related link to explain what's happening: https://stackoverflow.com/a/23086139

**Comment by jcs224** [comment]
You should be able to set the domain in Oak's `CookiesSetDeleteOptions`, which we reveal through `cookieSetOptions` when creating the session instance.

```ts
const store = new MemoryStore()

const session = new Session(store, {
  cookieSetOptions: {
    domain: 'api.example.com'
  }
});
```
