### ISSUE TITLE
Main readme example doesn't work with Oak current

### ISSUE THREAD

**Issue by cameronelliott** [jcs224/oak_sessions#17]
Hi, thanks for making this, it seems cool (and the Bedrock team selected it, so it must be good)!

I'm a not-so-good JS developer, but am experimenting with this.

I tried to use the Readme example with Deno, and got this error:
```
c@macmini ~/D/r/oak_sessions> deno run ./foo.ts
Check file:///Users/c/Documents/react/oak_sessions/foo.ts
error: TS2345 [ERROR]: Argument of type '(ctx: Context, next: () => Promise<unknown>) => Promise<void>' is not assignable to parameter of type 'Middleware<State, Context<State, AppState>>'.
  Types of parameters 'ctx' and 'context' are incompatible.
    Type 'Context<State, AppState>' is not assignable to type 'Context<State, Record<string, any>>'.
      Types of property 'app' are incompatible.
        Type 'Application<AppState>' is not assignable to type 'Application<Record<string, any>>'.
          Property '#contextState' in type 'Application' refers to a different member that cannot be accessed from within type 'Application'.
app.use(session.initMiddleware())
        ~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/c/Documents/react/oak_sessions/foo.ts:19:9
```

I had no idea what to do with that error.

Luckily, I found one of the Oak versions this was authored with in the file 'deps.ts'

By modifing the Readme example to use the same Oak version, the Readme example runs fine.

Maybe you want to change the Readme to include the Oak version, so it works for others out of the box?

Anyway, thanks for making & sharing this!

**Comment by jcs224** [comment]
Thanks for the feedback. This will become less of an issue when Deno stops type-checking when running a program by default, but it should be made more clear in the README for now.

Another way to solve this in the future if there's a version mismatch, just add the `--no-check` argument when running the app. This is the same behavior as Deno Deploy.

**Comment by jcs224** [comment]
Now that Deno 1.23 defaults to not running a type-check on `deno run` by default, the readme example should work regardless of type issues. It will still show up in the IDE text highlighting as an error, so we'll still have to keep up on the Oak version updates, but I'm sure we'll figure something out.

https://deno.com/blog/v1.23#no-type-checking-by-default

**Comment by jarrodu** [comment]
Any idea what we would need to do to fix the type error? I prefer to only ship code that type checks.
