### ISSUE TITLE
Sessions example seem to not be working  for new oak version

### ISSUE THREAD

**Issue by e-osuna-g** [jcs224/oak_sessions#43]
Following the example it breaks on this line it breaks on newest version on oak as well as on jsr:@oak/oak@^12.6.1

`app.use(Session.initMiddleware())`
this is the error showing
![image](https://github.com/user-attachments/assets/beab0b0e-8fe0-460d-987b-e6c6f87b7f2a)

**Comment by scottansell** [comment]
Same issue on my end with jsr:@oak/oak@^17.1.0

In addition to the type error my session state is not being preserved between requests.

**Comment by Kenya-West** [comment]
> In addition to the type error my session state is not being preserved between requests

Yes, can confirm the problem

**Comment by iuioiua** [comment]
Gentle ping, @jcs224

**Comment by jcs224** [comment]
Thanks for all of your input! I upgraded the package to work with the latest `17.x` version of Oak. The example in the readme should work now. It was really just a matter of changing the form input method:

From 
```ts
const form = await ctx.request.body({type: 'form'}).value
```

To
```ts
const form = await ctx.request.body.form()
```

As for data not persisting between the requests, @scottansell and @Kenya-West, please create a different issue if this latest update didn't work for you.
