### ISSUE TITLE
No overload matches session.initMiddleware() 

### ISSUE THREAD

**Issue by Sandroggy** [jcs224/oak_sessions#7]
Hi,

First i think that there is an error on the import of the usage section of the README
"https://deno.land/x/sessions/mod.ts" sould be "https://deno.land/x/oak_sessions/mod.ts" ?

I can't make the exemple in the readme work, i got an error 
```
TS2769 [ERROR]: No overload matches this call.
Type 'RouterContext<RouteParams, State>' is not assignable to type 'Context<State, Record<string, any>>'.
```
I use last version of both oak and oak_sessions

**Comment by jcs224** [comment]
Looking into this a little, it appears something in Oak changed from version 9.0.0 to 9.0.1.

In the meantime, it should work to just explicitly use Oak 9.0.0 to make this work again.

```ts
import { Application, Router } from "https://deno.land/x/oak@v9.0.0/mod.ts";
```

**Comment by jcs224** [comment]
The other option is to run the code with the `--no-check` CLI flag. This will skip TypeScript checking if you just want the app to run. A better long-term solution will be looked at.

**Comment by Sandroggy** [comment]
Thanks for the help :) !

**Comment by jcs224** [comment]
Fixed with https://github.com/jcs224/oak_sessions/commit/7645b590d39608d4172a1ed87839864f8c6baa39
