### ISSUE TITLE
Create DenoDB driver

### ISSUE THREAD

**Issue by jcs224** [jcs224/oak_sessions#9]

**Comment by jcs224** [comment]
DenoDB project seems to be on ice, closing for now.

**Comment by kinghat** [comment]
> DenoDB project seems to be on ice, closing for now.

ya i havent been paying any attention, do you know if anything else has taken its place?

**Comment by jcs224** [comment]
@kinghat Not sure, looking at the issues, people seem to be forking it quite a bit to meet their own needs. Would be nice to have a good Deno ORM.
